/* =========================================================
   MARVEL CHALLENGE - Base de données des personnages Marvel
   Grande base de personnages répartis par catégories
   ========================================================= */

const MARVEL_DATABASE = {

  avengers: [
    "Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye",
    "Vision", "Scarlet Witch", "War Machine", "Falcon", "Winter Soldier",
    "Ant-Man", "Wasp", "Captain Marvel", "Black Panther", "Doctor Strange",
    "Quicksilver", "Hercule", "She-Hulk", "Moon Knight", "Luke Cage",
    "Iron Fist", "Daredevil", "Jessica Jones", "Punisher", "Spectrum",
    "Wonder Man", "Sentry", "Songbird", "Photon", "Mockingbird",
    "Union Jack", "Living Lightning", "Tigra", "Stingray",
    "Jocasta", "Firebird", "Triathlon", "Jack of Hearts", "Yellowjacket",
    "Goliath", "Giant-Man", "Ironheart", "Captain Britain", "Echo",
    "Ronin", "Swordsman", "Marvel Boy", "3-D Man", "Docteur Druid",
    "Human Torch Original", "Toro", "Whizzer", "Blazing Skull",
    "Two-Gun Kid", "Red Wolf", "Gabriel Jones", "Dum Dum Dugan",
    "Thor Jane Foster", "Captain America Sam Wilson", "Vision Viv",
    "White Vision", "Wasp Nadia", "Sentinel of Liberty", "Frog-Man",
    "Rick Jones", "Spider-Man Ben Reilly", "Nomad", "Steve Rogers Captain America",
    "Captain America Isaiah Bradley", "Thunderstrike", "Devil-Slayer",
    "Darkstar Avengers", "Vance Astropowered", "Silverclaw Avengers",
    "Justice Avengers", "Firestar Avengers", "Speedball Avengers",
    "Gravity", "Slapstick", "Turbo", "Bantam",
    "Iron Patriot",
    "Ares Avengers",
    "Noh-Varr",
    "Moonstone",
    "Daken",
    "Void Sentry",
    "Warbird",
    "Binary",
    "Protector Avengers",
    "Red Hulk",
    "Skaar",
    "A-Bomb",
    "Doc Samson",
    "Quake",
    "Hellcat",
    "Patsy Walker",
    "Amadeus Cho Avengers",
    "Smart Hulk",
    "General Thunderbolt Ross",
    "Vision Aarkus",
    "Marvel Girl Carol",
    "Ultragirl",
    "Speedball New Warriors",
    "Nova Richard Rider Avengers",
    "Nova Sam Alexander Avengers",
    "Genis-Vell Avengers",
    "Songbird Force Works",
    "Meteorite",
    "Blizzard Hero Avengers",
    "Crystal Avengers",
    "Human Torch Avengers",
    "Sersi Avengers",
    "Black Knight",
    "Dane Whitman",
    "Ebony Blade Knight",
    "Two-Gun Kid Avengers",
    "Marvel Man Avengers",
    "Miss America Chavez Avengers",
    "Wiccan Avengers",
    "Hulkling Avengers",
    "Stature Avengers",
    "Patriot Avengers",
    "Vision Jonas",
    "Living Lightning Force Works",
    "War Machine Force Works",
    "Century Force Works",
    "U.S.Agent Force Works",
    "Scarlet Witch Force Works",
    "Wonder Man Force Works",
    "Spider-Woman Force Works",
    "Iron Man 2020",
    "Arno Stark",
    "Teen Tony",
    "Riri Williams Ironheart Avengers",
    "Kate Bishop Avengers",
    "Miles Morales Avengers",
    "Ms Marvel Kamala Avengers",
    "Squirrel Girl Avengers",
    "Silk Avengers",
    "Nadia Van Dyne Avengers",
    "Captain America Peggy Carter Alt",
    "Falcon Sam Wilson Cap",
    "Bucky Barnes Cap",
    "Iron Man Extremis",
    "Hulk Joe Fixit",
    "Thor Beta Ray Bill Avengers",
    "Black Panther Shuri Avengers",
    "Doctor Strange Sorcerer Avengers",
    "Ant-Man Scott Lang",
    "Ant-Man Hank Pym Original",
    "Wasp Janet Van Dyne Original",
    "Captain Marvel Mar-Vell Avengers",
    "Captain Marvel Monica Rambeau",
    "She-Hulk Avengers Member",
    "Vision Synthezoid Avengers",
    "Falcon Redwing Avengers",
    "Hawkeye Ronin Avengers",
    "Black Widow Yelena Avengers",
    "War Machine James Rhodes Avengers"
  ],

  spiderman: [
    "Spider-Man", "Miles Morales", "Spider-Gwen", "Spider-Man 2099",
    "Spider-Woman", "Silk", "Venom", "Carnage", "Green Goblin",
    "Docteur Octopus", "Vautour", "Sandman", "Electro", "Mysterio",
    "Rhino", "Scorpion", "Kraven le Chasseur", "Lizard", "Shocker",
    "Hobgoblin", "Chameleon", "Black Cat", "Jackal", "Tombstone",
    "Prowler", "Molten Man", "Morbius", "Puma", "Speed Demon",
    "Scarlet Spider", "Anti-Venom", "Toxin", "Hybrid", "Scream",
    "Lasher", "Riot", "Phage", "Agony", "Sleeper Venom", "Mania",
    "Spider-Man India", "Spider-Man Noir", "Spider-Ham", "Web-Slinger",
    "Silver Sable", "Paladin Spider", "Iron Spider", "Doppelganger",
    "Spider-Girl", "Madame Web", "Julia Carpenter", "Mattie Franklin",
    "Cindy Moon", "Ezekiel Sims", "Hammerhead Spider", "Shathra",
    "Mr. Negative", "Kingpin Spider", "Big Wheel", "Grizzly",
    "Beetle", "Boomerang Spider", "Trapster", "Rocket Racer",
    "Spot", "Screwball", "Digger", "Stegron",
    "Spider-Man Peter Parker Classic",
    "Spider-Man Symbiote Black Suit",
    "Spider-Man 1602",
    "Spider-Man Bombastic Bag-Man",
    "Ultimate Spider-Man",
    "Spider-Man Unlimited",
    "Six Arm Spider-Man",
    "Spider-Man Assassin Kaine",
    "Kaine Parker",
    "Ben Reilly Scarlet Spider Classic",
    "May Reilly Spider-Girl",
    "Spider-Man 2211",
    "Spider-UK",
    "Lady Spider",
    "Spider-Monkey",
    "Peni Parker",
    "SP Dr Spiderman",
    "Web Warriors Fusion",
    "Spider-Man China",
    "Spider-Man Ai Apaec",
    "Spider-Man Ero",
    "Aracely Penina",
    "Spider-Woman Julia Cornwall",
    "Spider-Girl Anya Corazon",
    "Araña Anya Corazon",
    "Bombshell Spider",
    "Spinneret",
    "White Rabbit Spider",
    "Clash Spiderman",
    "Overdrive Spiderman"
  ],

  xmen: [
    "Professeur X", "Cyclope", "Jean Grey", "Wolverine", "Tornade",
    "Malicia", "Diablo", "Iceberg", "Angel", "Gambit", "Jubilee",
    "Nightcrawler", "Colossus", "Kitty Pryde", "Psylocke", "Cable",
    "Bishop", "Magneto", "Mystique", "Serval", "Sabretooth", "Juggernaut",
    "Emma Frost", "Deadpool", "X-23", "Multiple Man", "Havok", "Polaris",
    "Banshee", "Sunfire", "Dazzler", "Longshot", "Forge", "Cannonball",
    "Sunspot", "Warpath", "Mirage", "Magik", "Northstar", "Domino",
    "Shatterstar", "Wolfsbane", "Rictor", "Boom-Boom", "Feral X-Force",
    "Marrow", "Maggott", "Chamber", "Skin X-Men", "Thunderbird",
    "Firestar Xmen", "Danielle Moonstar", "Karma", "Wolverine Laura",
    "Beast", "Nova X-Men Sam Guthrie", "Sage", "Fantomex", "Deathbird",
    "Selene", "Exodus", "Toad", "Pyro", "Avalanche", "Blob",
    "Mastermind", "Spiral", "Callisto", "Marauder Sabretooth",
    "Gladiator Morlocks", "Vanisher", "Arclight", "Harpoon",
    "Prism Marauder", "Scalphunter", "Riptide", "Blockbuster",
    "Weapon X", "Deadpool Wade Wilson", "Omega Red", "Lady Deathstrike",
    "Silver Samurai", "Gorgon Hand", "Random", "Maverick",
    "Kid Omega", "Hope Summers", "Kwannon", "Surge", "Anole",
    "Rockslide", "Pixie", "Prodigy", "Hellion",
    "Cyclops Corsair Alt",
    "Havok Xmen Alt",
    "Vulcan Xmen",
    "Rachel Summers",
    "Cable Nathan Summers Young",
    "Stryfe Xmen Clone",
    "Copycat Vanessa Xmen",
    "Sabra Xmen",
    "Dani Moonstar Xmen",
    "Berzerker Xmen",
    "Magma Xmen",
    "Warlock New Mutants",
    "Cypher New Mutants",
    "Wolfsbane New Mutants",
    "Karma New Mutants",
    "Boom Boom New Mutants",
    "Rictor New Mutants",
    "Sunspot New Mutants",
    "Cannonball New Mutants",
    "Magik New Mutants",
    "Moonstar New Mutants",
    "Legion Xavier Son",
    "Franklin Xmen Alt",
    "Jean Grey Phoenix Force",
    "Emma Frost White Queen Xmen",
    "Storm Ororo Munroe Xmen",
    "Beast Hank McCoy Xmen",
    "Angel Warren Worthington Xmen",
    "Archangel Xmen",
    "Colossus Piotr Rasputin Xmen",
    "Nightcrawler Kurt Wagner Xmen",
    "Gambit Remy LeBeau Xmen",
    "Rogue Anna Marie Xmen",
    "Bishop Lucas Xmen",
    "Cable Nathan Xmen",
    "Deadpool Wade Wilson Xmen",
    "X-23 Laura Kinney Xmen",
    "Jubilee Jubilation Lee Xmen",
    "Psylocke Betsy Braddock Xmen",
    "Iceman Bobby Drake Xmen"
  ],

  gardiens: [
    "Star-Lord", "Gamora", "Drax", "Rocket Raccoon", "Groot", "Mantis",
    "Nebula", "Yondu", "Adam Warlock", "Kraglin", "Cosmo", "Angela",
    "Moondragon", "Phyla-Vell", "Quasar", "Beta Ray Bill", "Vance Astro",
    "Martinex", "Charlie-27 Gardiens", "Major Victory", "Talon Fuma",
    "Aleta Ogord", "Nikki Gardiens", "Yellowjacket Gardiens",
    "Firelord Gardiens", "Starhawk", "Nova Prime", "Groot Junior",
    "Blastaar Gardiens", "Korath", "Ronan Gardiens", "Ravager Aleta",
    "Mainframe Gardiens", "Replica", "Praxagora", "Mother Nature",
    "Vance Astrovik", "Krugarr", "Bug Gardiens",
    "Star-Lord Peter Quill Full",
    "Gamora Zen Whoberi Full",
    "Drax Arthur Douglas Full",
    "Rocket Raccoon Full",
    "Groot Flora Colossus Full",
    "Mantis Empath Full",
    "Nebula Thanos Daughter Full",
    "Yondu Udonta Full",
    "Adam Warlock Cocoon Full",
    "Kraglin Obfonteri Full",
    "Cosmo Spacedog Full",
    "Angela Asgard Full",
    "Groot Baby Full",
    "Ravagers Yondu Crew",
    "Charlie-27 Gardiens Classic",
    "Martinex T'Naga Full",
    "Vance Astro Major Victory Full",
    "Nikki Gardiens Full",
    "Yellowjacket Vance Full",
    "Talon Fuma Full",
    "Aleta Ogord Starhawk Full",
    "Mainframe AI Full",
    "Replica Clone Full",
    "Praxagora Gardiens Full",
    "Bug Micronaut Full"
  ],

  fantasticfour: [
    "Mister Fantastic", "Invisible Woman", "Human Torch", "The Thing",
    "Franklin Richards", "Valeria Richards", "Docteur Fatalis", "Namor",
    "H.E.R.B.I.E.", "Uatu le Gardien", "Alicia Masters", "Puppet Master",
    "Klaw", "Diablo Fatal", "Impossible Man", "Moleman", "Annihilus FF",
    "Kang FF", "Psycho-Man", "Wizard FF", "Sandman FF", "Trapster FF",
    "Thundra", "Frankie Raye", "She-Hulk FF", "Ms. Marvel FF Sharon",
    "Crystal", "Medusa Inhumans", "Black Bolt", "Karnak",
    "Gorgon Inhumans", "Triton", "Lockjaw",
    "Reed Richards Mister Fantastic Full",
    "Sue Storm Invisible Woman Full",
    "Johnny Storm Human Torch Full",
    "Ben Grimm The Thing Full",
    "Doctor Doom Victor Von Fatalis Full",
    "Namor Sub-Mariner Full",
    "Silver Surfer Herald Full",
    "Galactus Devourer Full",
    "Uatu Watcher Full",
    "Black Panther FF Ally",
    "Franklin Richards Powerful Full",
    "Valeria Richards Genius Full",
    "Alicia Masters Blind Sculptor Full",
    "Herbie Robot Full",
    "Puppet Master Villain Full",
    "Mole Man Subterranean Full",
    "Impossible Man Shapeshifter Full",
    "Wizard Villain Full",
    "Trapster Paste Pot Pete Full",
    "Frankie Raye Nova Full"
  ],

  vilains: [
    "Thanos", "Loki", "Ultron", "Crâne Rouge", "M.O.D.O.K.", "Baron Zemo",
    "Kingpin", "Kang le Conquérant", "Ronan l'Accusateur", "Hela",
    "Killmonger", "Abomination", "Absorbing Man", "Bullseye", "Taskmaster",
    "Crossbones", "Whiplash", "Justin Hammer", "Aldrich Killian",
    "Malekith", "Dormammu", "Nightmare", "Mephisto", "Annihilus",
    "Sinistre", "Stryfe", "Onslaught", "Dark Phoenix", "Sentinelle",
    "Arcade", "Purple Man", "Owl", "Hammerhead Vilain", "Grand Maître",
    "Corvus Glaive", "Proxima Midnight", "Ebony Maw", "Cull Obsidian",
    "Blastaar", "Titania", "Ghost", "Arnim Zola", "Baron Mordo",
    "Enchanteresse", "Executioner", "Grim Reaper", "Batroc", "Constrictor",
    "Boomerang", "Living Laser", "Baron Strucker", "Viper Vilain",
    "Madame Hydra", "Grand Vizir Hydra", "Whirlwind", "Radioactive Man",
    "Titanium Man", "Melter", "Beetle Vilain", "Griffin", "Basilisk",
    "Serpent Society", "Diamondback Vilaine", "Cottonmouth", "Black Mariah",
    "Bushmaster", "Stilt-Man", "Wrecker", "Bulldozer", "Piledriver",
    "Thunderball", "Wrecking Crew", "Death Adder", "Cobra Vilain",
    "Mister Hyde", "Zzzax", "Leader", "Doc Samson Vilain", "U-Foes",
    "Vector", "X-Ray Vilain", "Ironclad", "Vapor Vilain", "Impossible Man Fils",
    "Super Skrull", "Skrull King", "Attuma", "Tiger Shark", "Byrrah",
    "Warlord Krang", "Egghead", "Porcupine", "Unicorn", "Grey Gargoyle",
    "Man-Bull", "Rhino Vilain", "Chemistro", "Blackout Vilain",
    "Blackheart", "Satana", "Chthon", "Belasco", "Marduk Kurios",
    "Salomé Mordo", "Baron Blood", "Dracula Marvel", "Morbius Vilain",
    "N'Kantu", "Doctor Doom Enfant", "Kristoff Vernard", "Rintrah",
    "Immortus", "Alioth", "Miss Sinistre Marauders", "Vertigo Marauders",
    "Malice Marauders", "Harpoon Marauders", "Blockbuster Marauders",
    "Nanny et Orphan-Maker", "Weapon X Programme", "Bastion",
    "Trask", "Master Mold", "Nimrod", "Cameron Hodge", "Fabian Cortez",
    "Holocaust", "Dark Beast", "Bishop Nemesis Trevor Fitzroy",
    "Skinjob", "Threnody", "Gauntlet Vilain", "Shinobi Shaw",
    "Black Tom Cassidy", "Erik le Rouge", "Mesmero", "Living Monolith",
    "Apocalypse Horsemen Famine", "Apocalypse Horsemen Pestilence",
    "Apocalypse Horsemen War", "Apocalypse Horsemen Death",
    "Red Ghost",
    "Super Apes",
    "Wizard Frightful Four",
    "Klaw Sound Villain",
    "Diablo Alchemist Villain",
    "Terrax Herald Villain",
    "Firelord Herald Villain",
    "Air-Walker Herald Villain",
    "Morg Herald Villain",
    "Stardust Herald Villain",
    "Possessor Herald Villain",
    "Hunger Herald Villain",
    "Devourer Galactus Herald",
    "Mangog",
    "Surtur",
    "Fenris Wolf Villain",
    "Jormungandr",
    "Ymir Frost Giant",
    "Laufey",
    "Amora Villain",
    "Skurge Villain",
    "Absorbing Man Creel",
    "Grey Gargoyle Villain",
    "Enchantress Villain Amora",
    "Mordred Villain",
    "Morgan le Fay",
    "Kulan Gath",
    "Chthon Villain",
    "Shuma-Gorath",
    "Cyttorak",
    "Nightmare Dream Villain",
    "Doctor Faustus",
    "Zemo Baron Helmut",
    "Crossfire Villain",
    "Machinesmith",
    "Deathwatch",
    "Hydra Supreme",
    "Baron Von Strucker",
    "Superia",
    "Femizons",
    "Grand Director",
    "Hate-Monger",
    "Sin Villain",
    "Master Man",
    "Warrior Woman Villain",
    "Iron Cross Villain",
    "U-Man",
    "Piranha Villain",
    "Orka Villain",
    "Llyra Villain",
    "Krang Villain"
  ],

  cosmique: [
    "Silver Surfer", "Galactus", "Nova", "Eternité", "Tribunal Vivant",
    "Gladiator", "Ikaris", "Sersi", "Thena", "Makkari", "Gilgamesh",
    "Sprite", "Phastos", "Druig", "Ajak", "Kro", "Genis-Vell", "Terrax",
    "Firelord", "Air-Walker", "Stardust", "Charlie-27", "Fenris",
    "Ego la Planète Vivante", "Celestials", "Arishem", "Uni-Mind",
    "Shalla-Bal", "Morg Cosmique", "Nova Corps", "Rhomann Dey",
    "Xandar", "Deathbird Cosmique", "Empereur D'Ken", "Vulcan Cosmique",
    "Impérial Guard Gladiator", "Smasher Impérial Guard",
    "Fang Impérial Guard", "Oracle Impérial Guard", "Astra Impérial Guard",
    "Nightside Impérial Guard", "Titan Cosmique", "A'lars Mentor",
    "Sui-San", "Eros Cosmique", "Champion de l'Univers", "In-Betweener",
    "Death Marvel", "Master Order", "Lord Chaos", "Epoch",
    "Infinity Entité", "Oblivion Entité", "Beyonder",
    "Annihilus Cosmic Ruler",
    "Blastaar Cosmic Ruler",
    "Maximus Inhuman",
    "Attilan Royal Family",
    "Lockjaw Teleporter",
    "Triton Inhuman Cosmic",
    "Karnak Inhuman Cosmic",
    "Gorgon Inhuman Cosmic",
    "Crystal Inhuman Cosmic",
    "Medusa Inhuman Queen",
    "Black Bolt Inhuman King",
    "Quicksilver Inhuman",
    "Ronan Kree Cosmic",
    "Mar-Vell Kree Cosmic",
    "Yon-Rogg Kree Cosmic",
    "Korath Kree Cosmic",
    "Supreme Intelligence Kree",
    "Ael-Dan Kree",
    "Zarek Kree",
    "Vox Kree",
    "Minn-Erva Kree",
    "Att-Lass Kree",
    "Bron-Char Kree",
    "Talos Skrull",
    "Soren Skrull"
  ],

  secondaires: [
    "Ms. Marvel", "Hawkeye Kate Bishop", "Squirrel Girl", "Moon Girl",
    "Devil Dinosaur", "Wiccan", "Speed", "Hulkling", "Patriot", "Stature",
    "America Chavez", "Elektra", "Blade", "Ghost Rider", "Cloak", "Dagger",
    "Werewolf by Night", "Man-Thing", "Howard le Canard", "Shang-Chi",
    "White Tiger", "Silverclaw", "Darkhawk", "Sleepwalker", "U.S.Agent",
    "Hyperion", "Blue Marvel", "Justice", "Firestar", "Speedball",
    "Agent Venom", "Jackpot", "Araña", "Silver Sable Secondaire",
    "Paladin", "Nick Fury", "Maria Hill", "Phil Coulson", "Sharon Carter",
    "Peggy Carter", "Yelena Belova", "Riri Williams", "Robbie Reyes",
    "Frank Castle", "Matt Murdock", "Foggy Nelson", "Karen Page",
    "Danny Rand", "Colleen Wing", "Misty Knight", "Trish Walker",
    "Malcolm Ducasse", "Heather Douglas", "Victor Alvarez", "Amadeus Cho",
    "Sam Wilson", "Doctor Voodoo", "Valkyrie", "Korg", "Miek",
    "Nico Minoru", "Karolina Dean", "Chase Stein",
    "Molly Hayes", "Gertrude Yorkes", "Alex Wilder", "Victor Mancha",
    "Old Lace", "Machine Man", "Darkstar", "Vindicator", "Guardian Canada",
    "Sasquatch", "Aurora Alpha Flight", "Shaman Alpha Flight",
    "Snowbird", "Puck Alpha Flight", "Talisman Alpha Flight",
    "Rage Secondaire", "Darkdevil", "Ka-Zar", "Shanna la Panthère",
    "Zabu", "Elsa Bloodstone", "Man-Wolf", "Angela Secondaire",
    "Gwenpool", "Squadron Supreme Hyperion", "Nighthawk Squadron",
    "Power Princess", "Doctor Spectrum", "Whizzer Squadron",
    "Nuke", "Sabra", "Union Jack Secondaire", "Captain UK",
    "Excalibur Meggan", "Captain Midlands", "Widget",
    "Feron", "Cerise", "Kylun", "Wild Child",
    "Cypher", "Warlock Techno-Organique", "Boom-Boom Secondaire",
    "Gauntlet", "Elixir", "Hellion Secondaire", "Mercury Xmen",
    "Rockslide Secondaire", "Anole Secondaire", "Surge Secondaire",
    "Match Xmen", "Wind Dancer", "Icarus Xmen", "Dust Xmen",
    "X-Man Nate Grey", "Bishop Secondaire", "Longshot Secondaire",
    "Random Secondaire", "Maverick Secondaire", "Garrison Kane",
    "Copycat", "Domino Secondaire", "Grizzly Secondaire",
    "Meltdown", "Siryn", "Warpath Secondaire", "Rictor Secondaire",
    "Wolfsbane Secondaire", "Feral Secondaire", "Cannonball Secondaire",
    "Sunspot Secondaire", "Roberto da Costa", "Amara Aquilla",
    "Empath X-Force", "Tarot X-Force", "Chamber Secondaire",
    "Husk", "Skids", "Wildchild", "Legion Xmen", "Proteus",
    "Mister Sinistre Clone", "Madelyne Pryor", "Nate Grey",
    "Bloodstorm", "Shard Xmen", "Sunder Xmen", "Cypher Secondaire",
    "Cecilia Reyes", "Marrow Secondaire", "Maggott Secondaire",
    "Chamber Xtreme", "Neal Shaara Thunderbird III",
    "Jubilee Secondaire", "M Monet St Croix", "Synch",
    "Everett Thomas", "Angelo Espinosa", "Skin Secondaire",
    "Penance Xtreme", "Beak", "Angel Salvadore", "Wallflower",
    "Hellion X23", "Mercury Secondaire", "Rockslide X",
    "Prodigy Secondaire", "Loa Xmen", "X-23 Secondaire",
    "Northstar Secondaire", "Aurora Secondaire", "Feral X-Factor",
    "Havok Secondaire", "Polaris Secondaire", "Strong Guy",
    "Wolfsbane X-Factor", "Multiple Man Secondaire",
    "Quicksilver Secondaire", "Wasp Secondaire",
    "Machine Man Secondaire", "Rom Spaceknight", "Devil Slayer",
    "Beast Boy Marvel", "Marvel Man", "Slapstick Secondaire",
    "Bantam Secondaire", "Turbo Secondaire", "Gravity Secondaire",
    "Rage Nextwave", "Boom-Boom Nextwave", "Machine Man Nextwave",
    "Tabitha Smith", "Elsa Bloodstone Nextwave", "Monica Rambeau",
    "Alpha Flight Marrina", "Marrina", "Box Alpha Flight",
    "Diamond Lil", "Radius Alpha Flight", "Manikin Alpha Flight",
    "Major Mapleleaf", "Wild Heart Alpha Flight", "Windshear",
    "Yukon Jack", "Nemesis Alpha Flight", "Northstar Fils",
    "Weapon Omega", "Vindicator Secondaire", "Purple Girl",
    "Laura Dean", "Flex Alpha Flight", "Coldfire", "Pathway",
    "Smart Alec Alpha Flight", "Task Force X", "Dreamqueen",
    "Loki Enfant", "Frog Thor", "Throg", "Beta Ray Bill Secondaire",
    "Volstagg", "Fandral", "Hogun", "Sif", "Balder", "Heimdall",
    "Odin", "Skurge", "Amora Enchanteresse Secondaire",
    "Karnilla", "Tyr Dieu", "Idunn", "Angela Thor",
    "Valkyrie Secondaire", "Kid Loki", "Old King Thor",
    "Beta Ray Bill Korbinite", "Jane Foster Valkyrie",
    "Roz Solomon", "Volstagg Secondaire", "Warriors Three",
    "Odinson", "Thori Chien de Thor", "Executioner Skurge Secondaire",
    "Absorbing Man Secondaire", "Titania Secondaire",
    "Radioactive Man Secondaire", "Wrecker Secondaire",
    "Namorita",
    "Wonder Man Simon Williams Full",
    "Vance Astrovik Full",
    "Justice League Marvel Ref",
    "Marvel Zombie Spider-Man",
    "Zombie Hunter Hulk",
    "Deathlok",
    "Meridian New Warriors",
    "Night Thrasher",
    "Namorita New Warriors",
    "Nova New Warriors",
    "Firestar New Warriors",
    "Speedball New Warriors Full",
    "Turbo New Warriors",
    "Bandit New Warriors",
    "Rage New Warriors",
    "Kymera New Warriors",
    "Debrii New Warriors",
    "Water Snake New Warriors",
    "Hindsight New Warriors",
    "Slapstick New Warriors",
    "Silhouette New Warriors",
    "Timeslip New Warriors",
    "Ultragirl New Warriors",
    "Dagger New Warriors",
    "Cloak New Warriors",
    "Powerhouse New Warriors",
    "Microbe New Warriors",
    "Chord New Warriors",
    "Aegis New Warriors",
    "Gauntlet New Warriors",
    "Dwayne Taylor Night Thrasher",
    "Robbie Baldwin Speedball",
    "Nova Sam Alexander Full",
    "Nova Richard Rider Full",
    "Marvel Boy Vance Astro Full",
    "Blue Streak",
    "Debrii Nolan",
    "Hummingbird New Warriors",
    "Longshot New Warriors",
    "Ricochet Spider Hero",
    "Prodigy David Alleyne Full",
    "Darkhawk Chris Powell Full",
    "Sleepwalker Rick Sheridan Full",
    "Terror Inc",
    "Shroud Vigilante",
    "Moon Knight Marc Spector Full",
    "Werewolf Jack Russell Full",
    "Man-Thing Ted Sallis Full",
    "Simon Garth Zombie",
    "Brother Voodoo Jericho Drumm Full",
    "Daimon Hellstrom Son of Satan",
    "Satana Hellstrom Full",
    "Modred the Mystic",
    "Doctor Voodoo Sorcerer Supreme Full",
    "Scarlet Witch Wanda Full",
    "Agatha Harkness",
    "Nico Minoru Staff of One Full",
    "Karolina Dean Majesdanian Full",
    "Chase Stein Fistigons Full",
    "Molly Hayes Superstrength Full",
    "Xavin Skrull Runaway",
    "Victor Mancha Robot Full",
    "Klara Prast Runaway",
    "Old Lace Dinosaur Full",
    "Gert Yorkes Telepath Full",
    "Alex Wilder Runaway Full",
    "Cloak Tyrone Johnson Full",
    "Dagger Tandy Bowen Full",
    "Elektra Natchios Assassin Full",
    "Bullseye Assassin Full",
    "Typhoid Mary",
    "Stone Daredevil Villain",
    "Owl Daredevil Villain",
    "Gladiator Daredevil Villain",
    "Bullseye Daredevil Villain",
    "Purple Man Daredevil Villain",
    "Mister Fear",
    "Ikari Elektra Clone",
    "Stick Daredevil Mentor",
    "Foggy Nelson Lawyer Full",
    "Karen Page Full",
    "White Tiger Hector Ayala Full",
    "Cage Power Man Full",
    "Iron Fist Danny Rand Full",
    "Colleen Wing Daughters of Dragon",
    "Misty Knight Daughters of Dragon",
    "Shang-Chi Master of Kung Fu Full",
    "Jimmy Woo Agents of Atlas",
    "Gorilla-Man Agents of Atlas",
    "Marvel Boy Agents of Atlas",
    "Venus Agents of Atlas",
    "Namora Agents of Atlas",
    "M-11 Human Robot Agents of Atlas",
    "Uranian Agents of Atlas",
    "Aero Marvel China",
    "Sword Master Marvel China",
    "Ren Kui China Hero",
    "Crescent Marvel China",
    "Snowfall Marvel China",
    "Wave Marvel China",
    "White Fox Marvel Korea",
    "Luna Snow Marvel Korea",
    "Io Marvel Brazil",
    "Nezha Marvel China",
    "August Master Marvel China",
    "Zhu Bajie Marvel China",
    "Wolverine Warpath Team",
    "X-Force Domino Full",
    "X-Force Cable Full",
    "X-Force Deadpool Full",
    "X-Force Warpath Full",
    "X-Force Sunspot Full",
    "X-Force Boom Boom Full",
    "Weapon H",
    "Weapon X Force",
    "Old Man Logan",
    "Wolverine X-23 Successor",
    "Honey Badger Gabby",
    "Daken Akihiro Full",
    "Sabretooth Victor Creed Full",
    "Mystique Raven Darkholme Full",
    "Destiny Irene Adler",
    "Toad Mortimer Toynbee Full",
    "Blob Fred Dukes Full",
    "Pyro St John Allerdyce Full",
    "Avalanche Dominic Petros Full",
    "Multiple Man Jamie Madrox Full",
    "Strong Guy Guido Carosella Full",
    "Wolfsbane Rahne Sinclair Full",
    "Banshee Sean Cassidy Full",
    "Siryn Theresa Cassidy Full",
    "Havok Alex Summers Full",
    "Polaris Lorna Dane Full",
    "Forge Weapon Smith Full",
    "Gambit Cajun Thief Full",
    "Rogue Powerhouse Full",
    "Iceman Bobby Frost Full",
    "Beast Blue Furry Full",
    "Angel Salvador Warren Full",
    "Firestar Angelica Jones Full"
  ]
};

// Regroupe tous les personnages dans un seul tableau pour le mode "Tous"
MARVEL_DATABASE.all = [].concat(
  MARVEL_DATABASE.avengers,
  MARVEL_DATABASE.spiderman,
  MARVEL_DATABASE.xmen,
  MARVEL_DATABASE.gardiens,
  MARVEL_DATABASE.fantasticfour,
  MARVEL_DATABASE.vilains,
  MARVEL_DATABASE.cosmique,
  MARVEL_DATABASE.secondaires
);

// Rend la base disponible globalement pour script.js
window.MARVEL_DATABASE = MARVEL_DATABASE;
